title:
  type: string
  default: "Интеграторы"
  description: "Введите заголовок"
category:
  type: list
  list_type: category
  default: ""
  description: "Выберите категорию"
max_list_length:
  type: enum
  default: 4
  choices:
    - 4
    - 8
    - 12
  description: "Сколько показывать в списке топиков?"
