title:
  type: string
  default: "Интеграторы"
  description: "Введите заголовок"
category:
  type: list
  list_type: category
  default: ""
  description: "Выберите категорию"
max_list_length:
  type: enum
  default: 3
  choices:
    - 3
    - 6
    - 9
  description: "Сколько показывать в списке топиков?"
